### ISSUE TITLE
Running with Docker

### ISSUE THREAD

**Issue by jettro** [pbartusch/smui#34]
I am going through the documentation, my Docker skills are not fantastic, would be great to get some examples of how to run SMUI using docker. Think about configuring the database connection and exposing ports, etc.

Can you extend the documentation with some examples?

The the below docker-compose I seem to be having something running.

```
version: "3"

services:
  solr:
    container_name: my_solr
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my_solr
    restart: "no"
    volumes:
      - "./solrdata/:/var/solr/"
    ports:
      - "8983:8983"

  db:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_DATABASE: 'smui'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'smui'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'smui'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql-db:/var/lib/mysql

  smui:
    image: pbartusch/smui
    restart: "no"
    environment:
      - "SMUI_DB_URL=jdbc:mysql://db:3306/smui?autoReconnect=true&useSSL=false"
    ports:
      - "9000:9000"
    expose:
      - '9000'
```

The final bit I need to figure out is how to write the config, at the moment I get this error:
play.api.UnexpectedException: Unexpected exception[IOException: Cannot run program "/smui/conf/smui2solr.sh": error=2, No such file or directory]
